---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

**Step 12.1**

* Devon’s note: No notable errors.

* Lucas’s note: The process was straightforward due to previous familiarity with Git.

* Eitan’s note: I have a GitHub account and was able to connect to GitHub.

* Sofi's note: I connected to GitHub (already had an account).

**Step 12.2**

* Devon’s note: No notable errors.

* Lucas’s note: Skipped the creation step since the repository was already set up on GitHub.

* Eitan’s note: I was able to create the repo on GitHub without issue.

* Sofi's note: Connected to the repo.

**Step 12.3**

* Devon’s note: No notable errors.

* Lucas’s note: I used RStudio to clone the existing GitHub repository using the HTTPS URL. In RStudio, I navigated to File > New Project > Version Control > Git, pasted the repository URL, and ensured the project directory name matched the repo name.

* Eitan’s note: I cloned the team repository onto my local machine inside a DS_202 folder.

* Sofi's note: Repo is cloned in my ds202 folder.

**Step 12.4**

* Devon’s note: No notable errors.

* Lucas’s note: Everything worked. The only thing I had to do first was pull the latest changes before pushing. After that, I modified the README.md file by adding a new line, saved the changes, and committed them using RStudio’s Git.

* Eitan’s note: I made local changes to this file and then I did `git add .` to stage those changes to be committed. Then I did `git commit -a` to commit all staged changes.

* Sofi's note: Made changes to the file and then committed.

**Step 12.5**

* Devon’s note: I had issues since I was signed in to my personal Git account. I fixed this by signing in to my school one on Git Desktop.

* Lucas’s note: Pushing the changes to GitHub worked without any issues. After committing, I simply clicked the green “Push” button in RStudio’s Git pane, and the updates were successfully sent to the remote repository.

* Eitan’s note: I did `git push` to push those changes to the remote server. No credential challenge was experienced.

* Sofi's note: No issues pushing.

**Step 12.6**

* Devon’s note: No notable errors.

* Lucas’s note: I went back to my repository in the browser and refreshed the page. The updated README.md file displayed the new line I added from RStudio.

* Eitan’s note: I went to my browser and checked GitHub and saw that the changes were propagated to the repository.

* Sofi’s note: Browser was updated like on my local machine.

**Step 12.7**

* Devon’s note: No notable errors.

* Lucas’s note: Nothing done for this step.

* Eitan’s note: Cleaning up the repo on my local machine was no issue.

* Sofi’s note: No errors.
